import { Product } from "./scraper";

export const fallbackProducts: Record<string, Product[]> = {
  audio: [
    {
      id: 6047,
      name: "SpaceBuds 2 AI Smart 45hrs Playtime True Wireless Earbuds",
      slug: "oraimo-spacebuds-2-true-wireless-earbuds-otw-631-spacegrey",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/MA/product/2026/04/14/OTW-631-SPACEGREY-MAIN.png",
      price: 4900,
      originalPrice: 5500,
      rating: 4.9,
      reviewCount: 327,
      tag: "New Arrival",
      features: ["AI Translation & Voice Prompt", "Infinite Light Effect"],
      category: "audio",
    },
    {
      id: 1605,
      name: "Necklace Lite Call Vibration Wireless Headphones",
      slug: "oraimo-necklace-lite-call-vibration-30-hrs-playtime-app-wireless-headphones",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/MA/product/2024/03/19/OEB-311.png",
      price: 1600,
      originalPrice: 3000,
      rating: 4.9,
      reviewCount: 20855,
      features: ["30Hr Playtime (Lights On)", "Vibration Notifications"],
      category: "audio",
    },
    {
      id: 2673,
      name: "SpaceBuds Neo Spatial Audio Earbuds",
      slug: "oraimo-spacebuds-neo-true-wireless-spatial-earbuds-otw-323",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/GH/product/2025/01/09/spacebuds-neo-otw-323.png",
      price: 1900,
      originalPrice: 2500,
      rating: 4.8,
      reviewCount: 4104,
      features: ["Noise Reduction in Call", "Sound360 Spatial Audio"],
      category: "audio",
    },
    {
      id: 2442,
      name: "SpaceBox 8W FM Wireless Speaker",
      slug: "fm-and-customizable-lights-and-eq-speaker-spacebox-obs-382",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/KE/product/2024/11/29/OBS-382-1080.png",
      price: 2500,
      originalPrice: 3500,
      rating: 4.8,
      reviewCount: 7238,
      tag: "APP Deal",
      features: ["Powerful & Punchy Bass", "Customizable Lights & EQ"],
      category: "audio",
    },
    {
      id: 2519,
      name: "SpaceBuds N ANC Wireless Earbuds",
      slug: "oraimo-spacebuds-n-active-noise-cancellation-38-hour-play-time-true-wireless-earbuds",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/KE/product/2024/12/20/OTW-626N-2.png",
      price: 2800,
      originalPrice: 3500,
      rating: 4.8,
      reviewCount: 4019,
      tag: "New Arrival",
      features: ["38-Hr Long Playtime", "Sound360 Spatial Audio"],
      category: "audio",
    },
    {
      id: 2683,
      name: "BoomPop Lite ENC Headphones",
      slug: "oraimo-boompoplite-enc-65hr-playtime-over-ear-wireless-headphones",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/KE/product/2025/02/07/OHP-317-BLACK.png",
      price: 3000,
      originalPrice: 4000,
      rating: 4.7,
      reviewCount: 3548,
      tag: "New Arrival",
      features: ["65Hr Playtime", "Environmental Noise Cancellation"],
      category: "audio",
    },
    {
      id: 1899,
      name: "SpaceBuds Hybrid ANC True Wireless Earbuds",
      slug: "oraimo-spacebuds-50db-anc-noise-cancelling-earbuds-with-personalized-voice-prompt",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/KE/product/2024/08/29/OTW-630.png",
      price: 4900,
      rating: 4.9,
      reviewCount: 4603,
      tag: "New Flagship",
      features: ["50dB Hybrid ANC Noise Cancellation", "Personalized Lighting Effect"],
      category: "audio",
    },
    {
      id: 3572,
      name: "BoomPop N Wireless Headphones",
      slug: "oraimo-boompop-n-wireless-headphones-ohp-915n",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/GH/product/2025/07/14/oraimo-Wireless-Headphones-BoomPop-N-OHP-915N-0.png",
      price: 3300,
      originalPrice: 5000,
      rating: 4.8,
      reviewCount: 1031,
      tag: "eShop Exclusive",
      features: ["Hybrid Noise Cancellation", "65-hr Long Playtime"],
      category: "audio",
    },
    {
      id: 3646,
      name: "SpaceBuds Lite Earbuds",
      slug: "oraimo-tws-spacebuds-lite-otw-324",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/KE/product/2025/08/14/OTW-324-1080-b.png",
      price: 1800,
      originalPrice: 2500,
      rating: 4.8,
      reviewCount: 1395,
      tag: "New Arrival",
      features: ["Sound360 Spatial Audio", "Smart Earbud Finder"],
      category: "audio",
    },
    {
      id: 3648,
      name: "OpenSnap Open-Ear Earbuds",
      slug: "oraimo-opensnap-clip-on-open-ear-true-wireless-headphones-opn-373",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/BD/product/2025/08/07/OPN-373-lightgold.png",
      price: 3400,
      originalPrice: 4500,
      rating: 4.8,
      reviewCount: 230,
      tag: "New Arrival",
      features: ["Compact & Comfortable", "Open-Ear Design"],
      category: "audio",
    },
    {
      id: 3919,
      name: "SpaceBuds Air Earbuds",
      slug: "oraimo-spacebuds-air-38-hours-smart-finder-true-wireless-earbuds-otw-324s",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/MA/product/2025/09/04/OTW-324S-1080-SB.png",
      price: 2000,
      originalPrice: 2800,
      rating: 4.8,
      reviewCount: 172,
      tag: "New Arrival",
      features: ["38-Hr Long Playtime", "Smart Earbud Finder"],
      category: "audio",
    },
    {
      id: 4277,
      name: "Necklace 5 ANC Neckband Earphones",
      slug: "oraimo-necklace5-40hrs-playtime-vibration-alerts-wireless-earphone-oeb-611",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/BD/product/2025/09/15/OEB-611-BLACK.png",
      price: 3300,
      originalPrice: 3800,
      rating: 4.8,
      reviewCount: 240,
      tag: "New Arrival",
      features: ["Personalized Vibration Alerts", "Sound 360 Spatial Audio"],
      category: "audio",
    },
  ],
  power: [
    {
      id: 5001,
      name: "Traveler 12 Byte Power Bank",
      slug: "oraimo-traveler-12-byte-power-bank",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/KE/product/2024/10/16/OPB-1205N.png",
      price: 1500,
      originalPrice: 2000,
      rating: 4.7,
      reviewCount: 1200,
      features: ["10000mAh Capacity", "Dual USB Output"],
      category: "power",
    },
    {
      id: 5002,
      name: "PowerNova QF1 22.5W Fast Charge Power Bank",
      slug: "oraimo-power-nova-qf1",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/MA/product/2025/10/11/OPB-7270Q-0.png",
      price: 3200,
      originalPrice: 4000,
      rating: 4.8,
      reviewCount: 890,
      tag: "New Arrival",
      features: ["22.5W Fast Charging", "20000mAh Capacity"],
      category: "power",
    },
    {
      id: 5003,
      name: "PowerCube 20 Chic Charger",
      slug: "oraimo-powercube-20-chic",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/MA/product/2025/10/11/OCW-5201U-CC54.png",
      price: 2800,
      originalPrice: 3500,
      rating: 4.7,
      reviewCount: 650,
      tag: "New Arrival",
      features: ["20W USB-C PD", "Compact Design"],
      category: "power",
    },
    {
      id: 5004,
      name: "Hydra 4 Car Charger",
      slug: "oraimo-hydra-4-car-charger",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/MA/product/2025/10/11/OCW-U160S-C55-1080-A1.png",
      price: 1800,
      originalPrice: 2200,
      rating: 4.6,
      reviewCount: 420,
      tag: "New Arrival",
      features: ["4-Port Fast Charging", "LED Display"],
      category: "power",
    },
    {
      id: 5005,
      name: "MagCable Magnetic Charging Cable",
      slug: "oraimo-magcable",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/MA/product/2025/10/11/RobustLine-lightning-cable-OCD-114L-black.png",
      price: 800,
      originalPrice: 1200,
      rating: 4.5,
      reviewCount: 340,
      features: ["Magnetic Connector", "Fast Data Transfer"],
      category: "power",
    },
  ],
  "smart-office": [
    {
      id: 6001,
      name: "Watch 6N Full Touch Color Screen Smart Watch",
      slug: "oraimo-watch-6n-full-touch-clolor-screen-smart-watch-osw-8000n",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/NG/product/2025/09/16/oraimo-smart-watch-watch-6n-osw-8000n-image-0.png",
      price: 4500,
      originalPrice: 6000,
      rating: 4.7,
      reviewCount: 8900,
      features: ["Full Touch Display", "Heart Rate Monitor"],
      category: "smart-office",
    },
    {
      id: 6002,
      name: "Watch Muse 1.32 AMOLED Smart Watch",
      slug: "oraimo-watch-muse-1.32-amoled-health-elegance-smart-watch",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/KE/product/2025/05/23/oraimo-watch-muse-OSW-831N-4.png",
      price: 5500,
      originalPrice: 7000,
      rating: 4.9,
      reviewCount: 2800,
      tag: "eShop Exclusive",
      features: ["AMOLED Display", "Health Monitoring"],
      category: "smart-office",
    },
    {
      id: 6003,
      name: "SmartLamp Tube RGB Color Modes Light",
      slug: "oraimo-smartlamp-tube-various-rgb-color-modes",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/KE/product/2024/10/16/OML-501A-680.png",
      price: 2200,
      originalPrice: 3000,
      rating: 4.6,
      reviewCount: 560,
      tag: "APP Offer",
      features: ["RGB Color Modes", "18 Hours Battery Life"],
      category: "smart-office",
    },
    {
      id: 6004,
      name: "ClickFlow Wireless Mouse",
      slug: "oraimo-workgrip-high-compatibility-ergonomic-design-wireless-mice",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/PK/product/2025/05/20/oraimo-mice-OF-M200N.png",
      price: 1500,
      originalPrice: 2000,
      rating: 4.5,
      reviewCount: 380,
      features: ["Ergonomic Design", "High Compatibility"],
      category: "smart-office",
    },
    {
      id: 6005,
      name: "FlowMotion Gesture Control Smart Tracking Tripod",
      slug: "oraimo-flowmotion-gesture-control-smart-tracking-tripod",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/KE/product/2025/02/13/OAT-201A.png",
      price: 5500,
      originalPrice: 7000,
      rating: 4.8,
      reviewCount: 290,
      features: ["Face Tracking", "Gesture Control"],
      category: "smart-office",
    },
  ],
  "personal-care": [
    {
      id: 7001,
      name: "EasyCut Hair Clipper",
      slug: "oraimo-easycut-hair-clipper-ocl-230",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/GH/product/2025/07/14/oraimo-Hair-Clipper-EasyCut-OCL-230-0.png",
      price: 1800,
      originalPrice: 2500,
      rating: 4.6,
      reviewCount: 1200,
      features: ["Precision Blades", "Cordless Design"],
      category: "personal-care",
    },
    {
      id: 7002,
      name: "EasyCut 2 10W Super Powerful Hair Clipper",
      slug: "oraimo-easycut-2-10w-super-powerful-quick-charge-hair-clipper-ocl-233n",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/KE/product/2026/04/28/OCL-233N-TITANIUM-MAINimage.png",
      price: 2800,
      rating: 4.7,
      reviewCount: 450,
      tag: "eShop Exclusive",
      features: ["10W Powerful Motor", "Quick Charge"],
      category: "personal-care",
    },
    {
      id: 7003,
      name: "SmartTrimmer Home Cordless Trimmer",
      slug: "smarttrimmer-home-cordless-powerful-electric-trimmer-otr-210",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/GH/product/2025/02/19/smarttrimmer-otr-210.png",
      price: 1500,
      originalPrice: 2000,
      rating: 4.5,
      reviewCount: 680,
      tag: "New Arrival",
      features: ["Cordless Design", "Powerful Motor"],
      category: "personal-care",
    },
  ],
  "home-appliances": [
    {
      id: 8001,
      name: "VoltBlend High-Speed Blender",
      slug: "oraimo-voltblend-high-speed-blender",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/MA/product/2025/10/11/oraimo-Blender-VoltBlend-OBL-582A-mainimage.png",
      price: 5500,
      originalPrice: 7000,
      rating: 4.7,
      reviewCount: 340,
      features: ["High-Speed Motor", "Multiple Speed Settings"],
      category: "home-appliances",
    },
    {
      id: 8002,
      name: "CordForce Flex Corded Stick Vacuum",
      slug: "oraimo-cordforce-flex-corded-stick-vacuum",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/MA/product/2025/10/11/oraimo-Corded-Stick-Vacuum-CordForce-Flex-OSV-252A.png",
      price: 8500,
      originalPrice: 10000,
      rating: 4.6,
      reviewCount: 180,
      features: ["Corded Power", "Flexible Design"],
      category: "home-appliances",
    },
    {
      id: 8003,
      name: "BrewDrip Drip Coffee Maker",
      slug: "oraimo-brewdrip-drip-coffee-maker",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/MA/product/2025/10/11/oraimo-Drip-Coffee-Maker-BrewDrip-OCF-201A-mainimage.png",
      price: 3500,
      originalPrice: 4500,
      rating: 4.5,
      reviewCount: 210,
      features: ["1.5L Capacity", "Keep Warm Function"],
      category: "home-appliances",
    },
  ],
  "wireless-stereo-earbuds": [
    {
      id: 6047,
      name: "SpaceBuds 2 AI Smart 45hrs Playtime True Wireless Earbuds",
      slug: "oraimo-spacebuds-2-true-wireless-earbuds-otw-631-spacegrey",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/MA/product/2026/04/14/OTW-631-SPACEGREY-MAIN.png",
      price: 4900,
      originalPrice: 5500,
      rating: 4.9,
      reviewCount: 327,
      tag: "New Arrival",
      features: ["AI Translation & Voice Prompt", "Infinite Light Effect"],
      category: "audio",
    },
    {
      id: 2673,
      name: "SpaceBuds Neo Spatial Audio Earbuds",
      slug: "oraimo-spacebuds-neo-true-wireless-spatial-earbuds-otw-323",
      image: "https://cdn-img.oraimo.com/fit-in/360x360/GH/product/2025/01/09/spacebuds-neo-otw-323.png",
      price: 1900,
      originalPrice: 2500,
      rating: 4.8,
      reviewCount: 4104,
      features: ["Noise Reduction in Call", "Sound360 Spatial Audio"],
      category: "audio",
    },
  ],
};

export function getFallbackProducts(categorySlug: string): Product[] {
  return fallbackProducts[categorySlug] || fallbackProducts["audio"] || [];
}
